### ISSUE TITLE
您好，使用您给出的训练代码进行训练时第1个epoch中间step处loss开始变为NAN，请问可能是什么原因？

### ISSUE THREAD

**Issue by kikyou-220** [tswang0116/TA-DCH#3]

**Comment by tswang0116** [comment]
请检查一下学习率等超参数设置是否合理。如果还出现问题，请说明一下是哪个阶段的第一个epoch的loss出现异常。

**Comment by kikyou-220** [comment]
您好，起初学习率使用的是给出的1e-4，尝试减小学习率为1e-5仍有问题。
是训练Generator和Discriminator时出现异常。
![图片](https://user-images.githubusercontent.com/88917518/219531880-42b137a6-6914-4cdd-a60e-d0076caf68ae.png)

**Comment by tswang0116** [comment]
原型学习阶段貌似已经出现了问题，C2I和C2T的mAP值异常，请再检查一下前一阶段的训练。
![image](https://user-images.githubusercontent.com/94093430/219532921-6e88ba6d-4134-4567-80bc-e2430fd2a377.png)
以上是一个正常训练的例子。

**Comment by kikyou-220** [comment]
我使用的均为您GitHub给出的代码未作更改，原型训练阶段的loss也和您正常训练的差不多，但是这个mAP值确实有古怪，我也不清楚是什么原因。
唯一不同的是我使用的imagenet-vgg-f.mat是我从https://www.vlfeat.org/matconvnet/models/beta16/处下载的（因为您没有给出链接），可能是预训练模型的问题造成的吗？
（环境我也使用的是您给出的配置，但是pillow您没有给出版本信息，因此我使用的是PIL 9.0.1）

**Comment by tswang0116** [comment]
链接：https://pan.baidu.com/s/1An_rvzU_VIbGTPwjMgDgGg?pwd=qcrw 
提取码：qcrw
请尝试一下利用上述imagenet-vgg-f.mat进行测试

**Comment by tswang0116** [comment]
我使用的pillow版本是8.3.2

**Comment by kikyou-220** [comment]
好的，谢谢您！
