### ISSUE TITLE
Could you please share the dataset in its original form，Thank you very much

### ISSUE THREAD

**Issue by tjuxiaoli** [tswang0116/TA-DCH#5]
Could you please share the dataset in its original form，

**Comment by tswang0116** [comment]
What datasets do you need in their original format? We have provided the processed data needed for our experiments. We are concerned that the direct provision of raw data may have copyright implications. The raw data of these datasets are publicly available online, and you can download them directly from the official website.

**Comment by tjuxiaoli** [comment]
Thank you for your message，i'll follow your advice and download the raw data directly from the official website
