### ISSUE TITLE
训练被攻击方法的疑问

### ISSUE THREAD

**Issue by tjuxiaoli** [tswang0116/TA-DCH#6]
请问在训练被攻击模型的时候（比如DCMH），根据链接给的被攻击模型能在本文的五个数据集上跑通吗，我只能跑通那个链接底下指定的数据集

**Comment by tswang0116** [comment]
需要修改给定链接下各被攻击模型源代码的数据加载方式，源代码中的数据集存储方式和我们给定数据集的存储方式有些不同（我们是利用h5py存储的），我们提供的数据集可以采用如下代码使用：
import h5py
def load_data(path):
    file = h5py.File(path)
    images = file['IAll'][:]
    labels = file['LAll'][:]
    tags = file['TAll'][:]
    file.close()
    images = images.transpose(3,2,0,1)
    labels = labels.transpose(1,0)
    tags = tags.transpose(1,0)
    return images, tags, labels

**Comment by tjuxiaoli** [comment]
感谢回复！
我参照您给出的办法做了相应修改以使模型接受不同数据集的输入，这里出现一个小问题，就是我在加载预训练模型vgg-f的条件下在flicker25k数据集上可以成功训练，map从一开使的5个点涨到7个点，但是我是使用其他四个数据集加载预训练模型的条件下训练map只能从开始的1或2个点涨到3或4个点，好似其他数据集上预训练模型没发挥作用，请问你们是否遇到过这个问题

**Comment by tswang0116** [comment]
好像没有遇到过这种情况，可以检查一下代码中相关实验设置是否正确

**Comment by tjuxiaoli** [comment]
好的，谢谢
